const rank={"A2.1":1,"A2.2":2,"B1.1":3,"B1.2":4};
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
const sha256=async s=>{const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')};
function pa2(x){x=Number(x);return Number.isFinite(x)?x>=6.5?'B1.1':x>=4.75?'A2.2':'A2.1':null}
function pa3(x){x=Number(x);return Number.isFinite(x)?x>=83?'B1.1':x>=63?'A2.2':'A2.1':null}
async function user(req,env){const t=(req.headers.get('cookie')||'').match(/xldv_session=([^;]+)/)?.[1];if(!t)return null;const r=await env.XLDV_DB.prepare('select s.token,s.expires_at,u.* from sessions s join users u on u.id=s.user_id where s.token=? and s.expires_at>? and u.active=1').bind(t,Date.now()).first();return r||null}
async function audit(env,u,action,entity='',id='',meta={}){if(!u)return;await env.XLDV_DB.prepare('insert into audit_log(actor_username,role,school,action,entity,entity_id,metadata) values(?,?,?,?,?,?,?)').bind(u.username,u.role,u.school||null,action,entity,id,JSON.stringify(meta)).run()}
function scope(u, q=[]){if(u.role==='CSGD')q.push(['school',u.school]);return q}
function matchRows(rows,u,p){return rows.filter(r=>u.role!=='CSGD'||r.school===u.school).filter(r=>!p.school||r.school===p.school).filter(r=>!p.cohort||r.cohort===p.cohort).filter(r=>!p.major||r.major===p.major).filter(r=>!p.level||r.best_level===p.level).filter(r=>!p.method||r.method===p.method).filter(r=>!p.alert||JSON.parse(r.alerts||'[]').length).filter(r=>!p.search||[r.mssv,r.full_name,r.major].some(x=>String(x||'').toLowerCase().includes(p.search.toLowerCase())))}
export async function onRequest(context){const {request,env}=context;const url=new URL(request.url);const path=url.pathname.replace(/^\/api\/?/,'');
 try{
  if(request.method==='POST'&&path==='login'){const {username,password}=await request.json();const u=await env.XLDV_DB.prepare('select * from users where username=? and active=1').bind(username||'').first();if(!u||u.password_hash!==(await sha256(password||'')))return json({error:'Sai tài khoản hoặc mật khẩu'},401);const token=crypto.randomUUID()+crypto.randomUUID();await env.XLDV_DB.prepare('insert into sessions(token,user_id,expires_at) values(?,?,?)').bind(token,u.id,Date.now()+8*3600*1000).run();await audit(env,u,'LOGIN','user',String(u.id));return new Response(JSON.stringify({user:{username:u.username,role:u.role,school:u.school}}),{headers:{'content-type':'application/json','set-cookie':`xldv_session=${token}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=28800`}})}
  const u=await user(request,env); if(!u)return json({error:'Chưa đăng nhập'},401);
  if(path==='logout'&&request.method==='POST'){await audit(env,u,'LOGOUT','user',String(u.id));return new Response('',{status:204,headers:{'set-cookie':'xldv_session=; Path=/; Max-Age=0'}})}
  if(path==='me')return json({username:u.username,role:u.role,school:u.school});
  if(path==='dashboard'){const p=Object.fromEntries(url.searchParams);let rows=await env.XLDV_DB.prepare('select * from students order by school,mssv limit 5000').all();rows=matchRows(rows.results,u,p);const levels={};const methods={};let alerts=0;for(const r of rows){const l=r.best_level||'Chưa xác định';levels[l]=(levels[l]||0)+1;const m=r.method||'Chưa xác định';methods[m]=(methods[m]||0)+1;if(JSON.parse(r.alerts||'[]').length)alerts++}await audit(env,u,'VIEW_DASHBOARD','dashboard','summary');return json({kpi:{total:rows.length,determined:rows.filter(r=>r.best_level).length,missing:rows.filter(r=>!r.best_level).length,alerts},levels:Object.entries(levels).map(([label,value])=>({label,value})),methods:Object.entries(methods).map(([label,value])=>({label,value})),serverTime:new Date().toISOString()})}
  if(path==='students'){const p=Object.fromEntries(url.searchParams);let rows=await env.XLDV_DB.prepare('select * from students order by school,mssv limit 5000').all();rows=matchRows(rows.results,u,p);await audit(env,u,'VIEW_STUDENTS','student','list',{count:rows.length});return json(rows)}
  if(path==='audit'){if(!['ADMIN','BGH'].includes(u.role))return json({error:'Không có quyền'},403);const rows=await env.XLDV_DB.prepare('select * from audit_log order by id desc limit 1000').all();return json(rows.results)}
  if(path==='import'&&request.method==='POST'){if(u.role!=='ADMIN')return json({error:'Không có quyền'},403);const body=await request.json();if(!Array.isArray(body.rows))return json({error:'rows phải là mảng'},400);await env.XLDV_DB.prepare('delete from students').run();const stmt=env.XLDV_DB.prepare('insert into students(mssv,full_name,school,cohort,major,pa2_score,pa2_level,pa3_score,pa3_level,best_level,method,status,alerts,registration_pa1,note,pa3_source) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');const batch=[];for(const r of body.rows){if(!r.mssv)continue;const a=[];const l2=pa2(r.pa2_score);const l3=pa3(r.pa3_score);const ms=[l2&&{m:'PA2',l:l2,s:r.pa2_score},l3&&{m:'PA3',l:l3,s:r.pa3_score}].filter(Boolean).sort((a,b)=>(rank[b.l]||0)-(rank[a.l]||0));if(new Set(ms.map(x=>x.l)).size>1)a.push('Kết quả các phương án khác mức');const best=ms[0];batch.push(stmt.bind(r.mssv,r.full_name,r.school,r.cohort,r.major,Number.isFinite(Number(r.pa2_score))?Number(r.pa2_score):null,l2,Number.isFinite(Number(r.pa3_score))?Number(r.pa3_score):null,l3,best?.l||null,best?.m||null,best?'Đã xác định':'Chưa xác định',JSON.stringify(a),r.registration_pa1||'',r.note||'','KQ_PA1 (nguồn legacy)'));}if(batch.length)await env.XLDV_DB.batch(batch);await audit(env,u,'IMPORT_EXCEL','student','bulk',{rows:batch.length});return json({ok:true,rows:batch.length})}
  return json({error:'Not found'},404)
 }catch(e){return json({error:e.message||String(e)},500)}
}
